spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://todolist.c55jrjs9yxoi.ap-northeast-2.rds.amazonaws.com:3306/todolist?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    database: mysql

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/todolist.p12
    key-store-password: qwer1234
    key-store-type: PKCS12
    key-alias: todolist


